### ISSUE TITLE
Modularize Codebase with Webpack/Vite

### ISSUE THREAD

**Issue by dhextras** [dhextras/freight-pallet-calc#3]
> - Note: Half of the issue has been solved already by pullreq [#7](https://github.com/dhextras/freight-pallet-calc/pull/7)

**Motivation**
> The current codebase lacks modularity and could benefit from a more organized structure. By modularizing the code using a bundler like Webpack or Vite, we aim to improve maintainability, reusability, and overall code structure.

**Implementation**
> Integrate Webpack/Vite to create a modular system for the existing codebase. This involves breaking down the code into manageable modules and using the bundler to handle dependencies efficiently.

**Testing**
> - Verify that the application functionalities remain unaffected after the modularization.
> - Check if the build process is successful using Webpack/Vite.
> - Ensure that the final bundle size is reasonable and optimized.
> - Make sure even after modularizing nothing changed on the user expirience nor on app logic

**Screenshots**
> Attach screenshots showing the modularized code structure and any relevant terminal outputs during the build process.

**Checklist**
> - [x] Build process is optimized.
> - [x] Webpack/Vite integrated successfully.
> - [ ] Application functionalities remain intact.
> - [ ] Code is organized into modules.

**Comment by JasonBoyett** [comment]
I'll pick this one up.

**Comment by dhextras** [comment]
> I'll pick this one up.

Thx for the heads up but just a suggestion u could take a look into the new issue posted (its super duper simple one) if u wanna understand the code better and go on with webpack issue or you can simply go with this ill fix it up right a way.
